name: smart_grid
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.7
  - ca-certificates=2024.9.24
  - intel-openmp=2021.4.0
  - libffi=3.4.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numexpr=2.8.4
  - openssl=3.0.15
  - packaging=24.1
  - pandas=2.0.3
  - pip=24.2
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - vc=14.40
  - vs2015_runtime=14.40.33807
  - wheel=0.44.0
  - pip:
    - absl-py==2.1.0
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.11
    - aiohttp-cors==0.7.0
    - aiosignal==1.3.1
    - ale-py==0.10.1
    - annotated-types==0.7.0
    - asttokens==2.4.1
    - async-timeout==5.0.1
    - attrs==24.2.0
    - backcall==0.2.0
    - cachetools==5.5.0
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - clarabel==0.9.0
    - click==8.1.7
    - cloudpickle==3.1.0
    - colorama==0.4.6
    - colorful==0.5.6
    - colorlover==0.3.0
    - comm==0.2.2
    - contourpy==1.1.1
    - cufflinks==0.17.3
    - cvxpy==1.5.2
    - cycler==0.12.1
    - decorator==5.1.1
    - distlib==0.3.9
    - dm-tree==0.1.8
    - ecos==2.0.14
    - executing==2.1.0
    - farama-notifications==0.0.4
    - filelock==3.16.1
    - fonttools==4.54.1
    - frozenlist==1.5.0
    - fsspec==2024.10.0
    - google-api-core==2.23.0
    - google-auth==2.36.0
    - google-auth-oauthlib==1.0.0
    - googleapis-common-protos==1.66.0
    - grpcio==1.68.0
    - gym-notices==0.0.8
    - gymnasium==1.0.0
    - idna==3.10
    - imageio==2.35.1
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - ipython==8.12.3
    - ipywidgets==8.1.5
    - jax-jumpy==1.0.0
    - jedi==0.19.1
    - jinja2==3.1.4
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyterlab-widgets==3.0.13
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - lz4==4.3.3
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mpmath==1.3.0
    - msgpack==1.1.0
    - multidict==6.1.0
    - networkx==3.1
    - numpy==1.24.4
    - oauthlib==3.2.2
    - opencensus==0.11.4
    - opencensus-context==0.1.3
    - opencv-python==4.10.0.84
    - osqp==0.6.7.post3
    - parso==0.8.4
    - patsy==0.5.6
    - pickleshare==0.7.5
    - pillow==10.4.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.3.6
    - plotly==5.24.1
    - prometheus-client==0.21.0
    - prompt-toolkit==3.0.48
    - propcache==0.2.0
    - proto-plus==1.25.0
    - protobuf==5.28.3
    - psutil==6.1.0
    - pure-eval==0.2.3
    - py-spy==0.4.0
    - pyarrow==17.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pydantic==2.10.2
    - pydantic-core==2.27.1
    - pygame==2.6.1
    - pygments==2.18.0
    - pyparsing==3.1.4
    - python-microgrid==1.4.1
    - pytz==2024.2
    - pywavelets==1.4.1
    - pyyaml==6.0.2
    - qdldl==0.1.7.post4
    - ray==2.10.0
    - referencing==0.35.1
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - rich==13.9.4
    - rpds-py==0.20.1
    - rsa==4.9
    - scikit-image==0.21.0
    - scipy==1.10.1
    - scs==3.2.7
    - shellingham==1.5.4
    - smart-open==7.0.5
    - stable-baselines3==2.4.0
    - stack-data==0.6.3
    - statsmodels==0.14.1
    - sympy==1.13.3
    - tenacity==9.0.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - tifffile==2023.7.10
    - torch==2.4.1
    - tqdm==4.66.5
    - traitlets==5.14.3
    - typer==0.13.1
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - urllib3==2.2.3
    - virtualenv==20.28.0
    - wcwidth==0.2.13
    - werkzeug==3.0.6
    - widgetsnbextension==4.0.13
    - wrapt==1.17.0
    - yarl==1.15.2
    - zipp==3.20.2
